export default function Home() {
  return (
    <h1 className="text-3xl font-bold underline">
      Hello world!
    </h1>
  )
}


// import Head from 'next/head'
// import Image from 'next/image'
// import '../styles/global.css'
// import Link from 'next/link'

// export default function Home() {
//   return (
//     <div className="text-yellow-400">
//       <Head>
//         <title>Trucker App :)</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className="text-yellow-400">
//         <h1 className={styles.title}>
//           <a> Hi! Welcome to the trucker app</a>
//         </h1>
//         <h1 className="text-5xl font-bold underline">
//           Hello world!
//         </h1>
//         <ul>
//           <li>
//             <Link href="/job_post/1">Go to Keto Ice cream job post (ID 1)</Link>
//           </li>
//           <li>
//             <Link href="/job_post/2?foo=bar">Go to Taylormade job post (ID 2)</Link>
//           </li>
//           <li>
//             <Link href="/job_post/abc/a-comment">
//               Go to 404 (TODO UNHANDLED)
//             </Link>
//           </li>
//         </ul>
//         <br></br>
//         <br></br>
//         <ul>
//           <li>
//             <Link href="/profile/1">Go to Tyler's profile(ID 1)</Link>
//           </li>
//           <li>
//             <Link href="/profile/2?foo=bar">Go to Ryan's profile(ID 2)</Link>
//           </li>
//         </ul>
//       </main>

//       <footer className={styles.footer}>
//         <p> this is my footer</p>
//       </footer>
//     </div>
//   )
// }
